// // shared/components/servicesItems.js
// // Services items

// export const coiffure = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

// export const maquillage = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

// export const onglerie = [
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
//         price: "180 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
//         price: "180 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 45'",
//         store: "5"
//     }, {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
//         price: "180 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 45'",
//         store: "5"
//     }, {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
//         price: "180 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 45'",
//         store: "5"
//     }, {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
//         price: "180 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 45'",
//         store: "5"
//     },
// ];

// export const epilation = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

// export const cils = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];
// export const massage = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "100 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

// export const soins = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

// export const mariee = [
//     {
//         //image: require('../../assets/services//images/brushing.jpg'),
//         name: "Brushing2",
//         desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
//         price: "110 dhs",
//         review: "⭐️ 4.8",
//         reviewCount: " (60 avis)",
//         capacity: " 3",
//         duration: " 30'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coupe.jpg'),
//         name: "Coupe sophitiquée",
//         desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
//         price: "180 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (120 avis)",
//         capacity: " 1",
//         duration: " 45'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/lissage.jpg'),
//         name: "Soins lissage",
//         desc: "Un lissage naturel et élégant sans formol.",
//         price: "790 dhs",
//         review: "⭐️ 4.5",
//         reviewCount: " (30 avis)",
//         capacity: " 1",
//         duration: " 120'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/chignon.jpg'),
//         name: "Chignon",
//         desc: "Fait par les meilleurs professionnels.",
//         price: "180 dhs",
//         review: "⭐️ 4.9",
//         reviewCount: " (60 avis)",
//         capacity: " 1",
//         duration: " 90'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/coloration.jpg'),
//         name: "Coloration",
//         desc: "Utilisant les meilleurs produits pour un résultat inégale.",
//         price: "1 190 dhs",
//         review: "⭐️ 4.2",
//         reviewCount: " (15 avis)",
//         capacity: " 3",
//         duration: " 150'",
//         store: "5"
//     },
//     {
//         //image: require('../../assets/services//images/extensions.jpg'),
//         name: "Extensions de cheveux",
//         desc: "Extensions de cheveux pour un look élégant et naturel.",
//         price: "290 dhs",
//         review: "⭐️ 4.4",
//         reviewCount: " (70 avis)",
//         capacity: " 2",
//         duration: " 60'",
//         store: "5"
//     },
// ];

export const tabbedSectionsTestIDs = Object.freeze({
  coiffure: "CoiffureTestID",
  maquillage: "MaquillageTestID",
  onglerie: "OnglerieTestID",
  epilation: "EpilationFoodTestID",
  cils: "CilsTestID",
  massage: "MassageTestID",
  soins: "SoinsTestID",
  mariee: "MarieeTestID",
});

export const CoiffureData = [
  {
    key: "Coiffure",
    tabTestID: tabbedSectionsTestIDs.coiffure,
    title: "Coiffure",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Maquillage",
    tabTestID: tabbedSectionsTestIDs.maquillage,
    title: "Maquillage",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Onglerie",
    tabTestID: tabbedSectionsTestIDs.onglerie,
    title: "Onglerie",
    data: [
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
        price: "180 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
        price: "180 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
        price: "180 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
        price: "180 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style",
        price: "180 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 45'",
        store: "5",
      },
    ],
  },
  {
    key: "Epilation",
    tabTestID: tabbedSectionsTestIDs.epilation,
    title: "Epilation",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Cils",
    tabTestID: tabbedSectionsTestIDs.cils,
    title: "Cils",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Massage",
    tabTestID: tabbedSectionsTestIDs.massage,
    title: "Massage",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "100 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Soins",
    tabTestID: tabbedSectionsTestIDs.soins,
    title: "Soins",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
  {
    key: "Mariee",
    tabTestID: tabbedSectionsTestIDs.mariee,
    title: "Mariee",
    data: [
      {
        //image: require('../../assets/services//images/brushing.jpg'),
        name: "Brushing2",
        desc: "Pour embéllir votre coupe et sublimer vos cheuveux.",
        price: "110 dhs",
        review: "⭐️ 4.8",
        reviewCount: " (60 avis)",
        capacity: " 3",
        duration: " 30'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coupe.jpg'),
        name: "Coupe sophitiquée",
        desc: "Coupe alliant élégance et modernité, mettant en valeur votre style.",
        price: "180 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (120 avis)",
        capacity: " 1",
        duration: " 45'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/lissage.jpg'),
        name: "Soins lissage",
        desc: "Un lissage naturel et élégant sans formol.",
        price: "790 dhs",
        review: "⭐️ 4.5",
        reviewCount: " (30 avis)",
        capacity: " 1",
        duration: " 120'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/chignon.jpg'),
        name: "Chignon",
        desc: "Fait par les meilleurs professionnels.",
        price: "180 dhs",
        review: "⭐️ 4.9",
        reviewCount: " (60 avis)",
        capacity: " 1",
        duration: " 90'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/coloration.jpg'),
        name: "Coloration",
        desc: "Utilisant les meilleurs produits pour un résultat inégale.",
        price: "1 190 dhs",
        review: "⭐️ 4.2",
        reviewCount: " (15 avis)",
        capacity: " 3",
        duration: " 150'",
        store: "5",
      },
      {
        //image: require('../../assets/services//images/extensions.jpg'),
        name: "Extensions de cheveux",
        desc: "Extensions de cheveux pour un look élégant et naturel.",
        price: "290 dhs",
        review: "⭐️ 4.4",
        reviewCount: " (70 avis)",
        capacity: " 2",
        duration: " 60'",
        store: "5",
      },
    ],
  },
];
